# This file is part of project link.developers/ld-node-camera-basler.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers.beta/ld-node-camera-basler.
#
# SPDX-License-Identifier: MPL-2.0

package:
  name: "ld-node-camera-basler"
  version: {{ BUILD_VERSION }}

source:
  git_url: ../

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ld-cmake-tools
    - flatc

  host:
    - link2-cpp
    - ld-lib-image
    - pylonsdk
    - opencv

  run:
    - link2
    - pylonsdk

test:
  commands:
    - "ld-node-camera-basler --help"

extra:
  git-commit: {{ GIT_FULL_HASH }}

about:
  home: "https://gitlab.com/link.developers.beta/ld-node-camera-basler"
  license: "MPL-2.0"
  license_file: "LICENSE"
  summary: "A link2 node to access the basler camera using the pylon sdk"
